modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
[[mods]]
modId="resourcesheep"
version="${file.jarVersion}"
displayName="Resource Sheep"
# We'll work on this later - logoFile="examplemod.png"
credits="All thanks to me, and my minecraft crew"
authors="TheZaNmAN"
description='''
A mod that takes another approach to resource gathering, feeding a nuturing sheep that will produce you resources.

Stay Tuned!
'''
[[dependencies.resourcesheep]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.resourcesheep]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
